CREATE DATABASE DECELIS2RP;
GO

USE DECELIS2RP;
GO

CREATE TABLE userType (
   idUserType SMALLINT PRIMARY KEY IDENTITY NOT NULL,
   titleUserType VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE statusType (
   idStatus SMALLINT PRIMARY KEY IDENTITY NOT NULL ,
   activeStatus BIT NOT NULL
);
GO

CREATE TABLE timeClass (
   idTime  SMALLINT PRIMARY KEY IDENTITY NOT NULL,
   periodTime VARCHAR(50) NOT NULL
);
GO

CREATE TABLE skillLevel (
  idLevel SMALLINT PRIMARY KEY IDENTITY NOT NULL,
  skillLevel VARCHAR(50) NOT NULL
);
GO

CREATE TABLE class (
   idClass INT PRIMARY KEY IDENTITY NOT NULL,
   idLevel SMALLINT FOREIGN KEY REFERENCES skillLevel(idLevel),
   idTime SMALLINT FOREIGN KEY REFERENCES timeClass(idTime),
   nameClass VARCHAR(100) NOT NULL
);
GO

CREATE TABLE userInfo (
   idUser UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
   idUserType SMALLINT FOREIGN KEY REFERENCES userType(idUserType),
   idStatus SMALLINT FOREIGN KEY REFERENCES statusType(idStatus),
   idClass INT FOREIGN KEY REFERENCES class(idClass),
   nameUser VARCHAR(150) NOT NULL,
   email VARCHAR(256) NOT NULL,
   passwordUser VARCHAR(300) NOT NULL,
   userImage VARCHAR(300) 
);
GO

